MONITORING_ADDR ?= 127.0.0.1:8080
MONITORING_WEB_DIR ?= svelte-mpa/dist
MONITORING_TLS_CERT ?=
MONITORING_TLS_KEY ?=
MONITORING_AUTH_TOKEN ?=
MONITORING_READ_HEADER_TIMEOUT ?= 5s
MONITORING_IDLE_TIMEOUT ?= 2m
NODE_ID ?=
TOPOLOGY_PATH ?=
ELECTION_TIMEOUT ?= 15s
REPLICATION ?= false
REPLICATION_ASYNC ?= false
REPLICATION_QUEUE_SIZE ?= 1024
REPLICATION_RETRY_INTERVAL ?= 250ms
REPLICATION_MAX_ATTEMPTS ?= 3
REPLICATION_WIRE_FORMAT ?=
REPLICATION_SYNC_INTERVAL ?= 0
REPLICATION_SYNC_PREFIX ?=
ENFORCE_LEADER_WRITES ?= false
GRPC_ADDR ?=
DB_PATH ?=
DB_FORMAT ?=
DB_SYNC_INTERVAL ?= 0
DB_HOT_LOAD ?= false
DB_HOT_LOAD_MAX_BYTES ?= 1024
DB_HOT_LOAD_MAX_AGE ?= 1h
DB_HOT_LOAD_MIN_HITS ?= 1000
SNAPSHOT_PATH ?=
SNAPSHOT_INTERVAL ?= 0
SNAPSHOT_FORMAT ?=
JOURNAL_PATH ?=
JOURNAL_FORMAT ?=
JOURNAL_PULL_SOURCE ?=
JOURNAL_PULL_STATE_PATH ?=
JOURNAL_PULL_INTERVAL ?= 0
JOURNAL_PULL_TIMEOUT ?= 30s
JOURNAL_PULL_LIMIT ?= 0
JOURNAL_PULL_MAX_BATCHES ?= 0
DATA_DIR ?= data
BACKUP_DIR ?= backup/latest
BACKUP_OVERWRITE ?= false
RESTORE_OVERWRITE ?= false
SANITIZE_C ?= auto
SANITIZE_C_ALLOW_STRICT_OVERCOMMIT ?= 0
SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM ?= 0
SANITIZE_C_OVERCOMMIT_MEMORY_PATH ?=
SANITIZE_C_MEMINFO_PATH ?=
SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB ?=
BENCH ?= .
BENCHTIME ?=
COUNT ?= 1
SERIALIZATION_BENCH ?=
REDIS_HOST ?= 127.0.0.1
REDIS_PORT ?= 6379
REDIS_REQUESTS ?= 100000
REDIS_CLIENTS ?= 1
REDIS_KEYSPACE ?= 10000
REDIS_START_DOCKER ?= 0
REDIS_DOCKER_IMAGE ?= redis:7.0.4
TARANTOOL_REQUESTS ?= 10000
TARANTOOL_KEYSPACE ?= 10000
TARANTOOL_MEMTX_MEMORY ?= 268435456
TARANTOOL_BIN ?= tarantool
TARANTOOL_WORK_DIR ?=
HATRIE_COMMAND_BENCH ?= ^BenchmarkCommandFeature$$

.PHONY: test verify verify-go verify-race verify-c verify-frontend verify-ops backup restore bench bench-serialization bench-command-features bench-hatrie-command-features bench-redis-command-features bench-tarantool-command-features command-support run generate-proto cli monitoring-server frontend-install frontend-dev frontend-check frontend-test frontend-build

test: verify-go

verify: verify-go verify-c verify-frontend verify-ops

verify-go:
	./scripts/verify-go.sh

verify-race:
	./scripts/verify-race.sh

verify-c:
	./scripts/verify-c-policy-test.sh
	SANITIZE_C='$(SANITIZE_C)' SANITIZE_C_ALLOW_STRICT_OVERCOMMIT='$(SANITIZE_C_ALLOW_STRICT_OVERCOMMIT)' SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM='$(SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM)' SANITIZE_C_OVERCOMMIT_MEMORY_PATH='$(SANITIZE_C_OVERCOMMIT_MEMORY_PATH)' SANITIZE_C_MEMINFO_PATH='$(SANITIZE_C_MEMINFO_PATH)' SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB='$(SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB)' ./scripts/verify-c.sh

verify-frontend:
	./scripts/frontend.sh verify

verify-ops:
	./scripts/verify-ops.sh

backup:
	DATA_DIR='$(DATA_DIR)' BACKUP_DIR='$(BACKUP_DIR)' BACKUP_OVERWRITE='$(BACKUP_OVERWRITE)' ./scripts/backup.sh

restore:
	DATA_DIR='$(DATA_DIR)' BACKUP_DIR='$(BACKUP_DIR)' RESTORE_OVERWRITE='$(RESTORE_OVERWRITE)' ./scripts/restore.sh

bench:
	go test -run '^$$' -bench='$(BENCH)' -benchmem

bench-serialization:
	SERIALIZATION_BENCH='$(SERIALIZATION_BENCH)' BENCHTIME='$(BENCHTIME)' COUNT='$(COUNT)' ./scripts/benchmark-serialization.sh

bench-command-features:
	go test -run '^$$' -bench='^BenchmarkCommandFeature$$' -benchmem -count='$(COUNT)' $(if $(BENCHTIME),-benchtime='$(BENCHTIME)')

bench-hatrie-command-features:
	HATRIE_BENCH='$(HATRIE_COMMAND_BENCH)' BENCHTIME='$(BENCHTIME)' COUNT='$(COUNT)' ./scripts/benchmark-hatrie-command-features.sh

bench-redis-command-features:
	REDIS_HOST='$(REDIS_HOST)' REDIS_PORT='$(REDIS_PORT)' REDIS_REQUESTS='$(REDIS_REQUESTS)' REDIS_CLIENTS='$(REDIS_CLIENTS)' REDIS_KEYSPACE='$(REDIS_KEYSPACE)' REDIS_START_DOCKER='$(REDIS_START_DOCKER)' REDIS_DOCKER_IMAGE='$(REDIS_DOCKER_IMAGE)' ./scripts/benchmark-redis-command-features.sh

bench-tarantool-command-features:
	TARANTOOL_REQUESTS='$(TARANTOOL_REQUESTS)' TARANTOOL_KEYSPACE='$(TARANTOOL_KEYSPACE)' TARANTOOL_MEMTX_MEMORY='$(TARANTOOL_MEMTX_MEMORY)' TARANTOOL_BIN='$(TARANTOOL_BIN)' TARANTOOL_WORK_DIR='$(TARANTOOL_WORK_DIR)' ./scripts/benchmark-tarantool-command-features.sh

command-support:
	./scripts/command-support.sh

run:
	@CMD='$(CMD)' ./scripts/run.sh

generate-proto:
	./scripts/generate-proto.sh

cli:
	./scripts/cli.sh $(ARGS)

monitoring-server:
	MONITORING_ADDR='$(MONITORING_ADDR)' MONITORING_WEB_DIR='$(MONITORING_WEB_DIR)' MONITORING_TLS_CERT='$(MONITORING_TLS_CERT)' MONITORING_TLS_KEY='$(MONITORING_TLS_KEY)' MONITORING_AUTH_TOKEN='$(MONITORING_AUTH_TOKEN)' MONITORING_READ_HEADER_TIMEOUT='$(MONITORING_READ_HEADER_TIMEOUT)' MONITORING_IDLE_TIMEOUT='$(MONITORING_IDLE_TIMEOUT)' NODE_ID='$(NODE_ID)' TOPOLOGY_PATH='$(TOPOLOGY_PATH)' ELECTION_TIMEOUT='$(ELECTION_TIMEOUT)' REPLICATION='$(REPLICATION)' REPLICATION_ASYNC='$(REPLICATION_ASYNC)' REPLICATION_QUEUE_SIZE='$(REPLICATION_QUEUE_SIZE)' REPLICATION_RETRY_INTERVAL='$(REPLICATION_RETRY_INTERVAL)' REPLICATION_MAX_ATTEMPTS='$(REPLICATION_MAX_ATTEMPTS)' REPLICATION_WIRE_FORMAT='$(REPLICATION_WIRE_FORMAT)' REPLICATION_SYNC_INTERVAL='$(REPLICATION_SYNC_INTERVAL)' REPLICATION_SYNC_PREFIX='$(REPLICATION_SYNC_PREFIX)' ENFORCE_LEADER_WRITES='$(ENFORCE_LEADER_WRITES)' GRPC_ADDR='$(GRPC_ADDR)' DB_PATH='$(DB_PATH)' DB_FORMAT='$(DB_FORMAT)' DB_SYNC_INTERVAL='$(DB_SYNC_INTERVAL)' DB_HOT_LOAD='$(DB_HOT_LOAD)' DB_HOT_LOAD_MAX_BYTES='$(DB_HOT_LOAD_MAX_BYTES)' DB_HOT_LOAD_MAX_AGE='$(DB_HOT_LOAD_MAX_AGE)' DB_HOT_LOAD_MIN_HITS='$(DB_HOT_LOAD_MIN_HITS)' SNAPSHOT_PATH='$(SNAPSHOT_PATH)' SNAPSHOT_INTERVAL='$(SNAPSHOT_INTERVAL)' SNAPSHOT_FORMAT='$(SNAPSHOT_FORMAT)' JOURNAL_PATH='$(JOURNAL_PATH)' JOURNAL_FORMAT='$(JOURNAL_FORMAT)' JOURNAL_PULL_SOURCE='$(JOURNAL_PULL_SOURCE)' JOURNAL_PULL_STATE_PATH='$(JOURNAL_PULL_STATE_PATH)' JOURNAL_PULL_INTERVAL='$(JOURNAL_PULL_INTERVAL)' JOURNAL_PULL_TIMEOUT='$(JOURNAL_PULL_TIMEOUT)' JOURNAL_PULL_LIMIT='$(JOURNAL_PULL_LIMIT)' JOURNAL_PULL_MAX_BATCHES='$(JOURNAL_PULL_MAX_BATCHES)' ./scripts/monitoring-server.sh

frontend-install:
	./scripts/frontend.sh install

frontend-dev:
	./scripts/frontend.sh dev

frontend-check:
	./scripts/frontend.sh check

frontend-test:
	./scripts/frontend.sh test

frontend-build:
	./scripts/frontend.sh build
