MONITORING_ADDR ?= 127.0.0.1:8080
MONITORING_WEB_DIR ?= svelte-mpa/dist
MONITORING_TLS_CERT ?=
MONITORING_TLS_KEY ?=
MONITORING_AUTH_TOKEN ?=
AUDIT_LOG_PATH ?=
WRITE_PROTECTION ?= false
RATE_LIMIT ?= 0
MONITORING_READ_HEADER_TIMEOUT ?= 5s
MONITORING_IDLE_TIMEOUT ?= 2m
NODE_ID ?=
TOPOLOGY_PATH ?=
ELECTION_TIMEOUT ?= 15s
REPLICATION ?= false
REPLICATION_ASYNC ?= false
REPLICATION_QUEUE_SIZE ?= 1024
REPLICATION_RETRY_INTERVAL ?= 250ms
REPLICATION_MAX_ATTEMPTS ?= 3
REPLICATION_DEAD_LETTER_LIMIT ?= 128
REPLICATION_OUTBOX_PATH ?=
REPLICATION_OUTBOX_FORMAT ?= auto
REPLICATION_CIRCUIT_BREAKER_FAILURES ?= 5
REPLICATION_CIRCUIT_BREAKER_COOLDOWN ?= 30s
REPLICATION_WIRE_FORMAT ?=
REPLICATION_AUTH_TOKEN ?=
REPLICATION_SYNC_INTERVAL ?= 0
REPLICATION_SYNC_PREFIX ?=
ENFORCE_LEADER_WRITES ?= false
GRPC_ADDR ?=
GRPC_TLS_CERT ?=
GRPC_TLS_KEY ?=
GRPC_CLIENT_CA ?=
DB_PATH ?=
DB_FORMAT ?=
DB_SYNC_INTERVAL ?= 0
DB_COMPACT_INTERVAL ?= 0
DB_COMPACT_START_KEY ?=
DB_COMPACT_LIMIT_KEY ?=
DB_HOT_LOAD ?= false
DB_HOT_LOAD_MAX_BYTES ?= 1024
DB_HOT_LOAD_MAX_AGE ?= 1h
DB_HOT_LOAD_MIN_HITS ?= 1000
SNAPSHOT_PATH ?=
SNAPSHOT_INTERVAL ?= 0
SNAPSHOT_FORMAT ?=
JOURNAL_PATH ?=
JOURNAL_FORMAT ?=
JOURNAL_PULL_SOURCE ?=
JOURNAL_PULL_STATE_PATH ?=
JOURNAL_PULL_INTERVAL ?= 0
JOURNAL_PULL_TIMEOUT ?= 30s
JOURNAL_PULL_LIMIT ?= 0
JOURNAL_PULL_MAX_BATCHES ?= 0
DATA_DIR ?= data
BACKUP_DIR ?= backup/latest
BACKUP_OVERWRITE ?= false
RESTORE_OVERWRITE ?= false
DOCTOR_PATH ?= $(BACKUP_DIR)
RESTORE_BUNDLE_PATH ?= backup/latest.tar.gz
RESTORE_BUNDLE_OVERWRITE ?= false
RESTORE_REHEARSAL_PATH ?= $(BACKUP_DIR)
RESTORE_REHEARSAL_WORK_DIR ?=
RESTORE_REHEARSAL_KEEP_WORK_DIR ?= false
RESTORE_REHEARSAL_RUNTIME_CHECK ?= true
RESTORE_REHEARSAL_RUNTIME_GET ?=
RESTORE_REHEARSAL_RUNTIME_SERVER_BIN ?=
CLUSTER_PEER ?= http://127.0.0.1:8080
CLUSTER_PROBE_NODES ?= true
STORAGE_PEER ?= http://127.0.0.1:8080
STORAGE_COMPACT_START_KEY ?=
STORAGE_COMPACT_LIMIT_KEY ?=
SANITIZE_C ?= auto
SANITIZE_C_ALLOW_STRICT_OVERCOMMIT ?= 0
SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM ?= 0
SANITIZE_C_OVERCOMMIT_MEMORY_PATH ?=
SANITIZE_C_MEMINFO_PATH ?=
SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB ?=
BENCH ?= .
BENCHTIME ?=
COUNT ?= 1
SERIALIZATION_BENCH ?=
REDIS_HOST ?= 127.0.0.1
REDIS_PORT ?= 6379
REDIS_REQUESTS ?= 100000
REDIS_CLIENTS ?= 1
REDIS_KEYSPACE ?= 10000
REDIS_START_DOCKER ?= 0
REDIS_DOCKER_IMAGE ?= redis:7.0.4
BENCHMARK_ARTIFACT_DIR ?=
TARANTOOL_REQUESTS ?= 10000
TARANTOOL_KEYSPACE ?= 10000
TARANTOOL_MEMTX_MEMORY ?= 268435456
TARANTOOL_BIN ?= tarantool
TARANTOOL_WORK_DIR ?=
HATRIE_COMMAND_BENCH ?= ^BenchmarkCommandFeature$$
HATRIE_TRANSPORT_BENCH ?= ^BenchmarkCommandTransportFeature$$
BENCH_CI_SMOKE_BENCHTIME ?= 5x
BENCH_CI_SMOKE_COUNT ?= 1
BENCH_CI_SMOKE_COMMAND_BENCH ?= ^BenchmarkCommandFeature/(StringGet|ReservoirSampleAdd)$$
BENCH_CI_SMOKE_TRANSPORT_BENCH ?= ^BenchmarkCommandTransportFeature/InProcess/(StringSet|StringGet)$$
BENCH_CI_SMOKE_SERIALIZATION_BENCH ?= Benchmark(CommandWireJSON|CommandWireProtobuf)$$
BENCH_CI_SMOKE_CHECK_THRESHOLDS ?= 0
BENCH_CI_SMOKE_MAX_COMMAND_NS_OP ?= 250000
BENCH_CI_SMOKE_MAX_TRANSPORT_NS_OP ?= 500000
BENCH_CI_SMOKE_MAX_SERIALIZATION_NS_OP ?= 250000
BENCH_CI_SMOKE_MAX_B_OP ?= 1048576
BENCH_CI_SMOKE_MAX_ALLOCS_OP ?= 512
BENCH_CI_SMOKE_ARTIFACT_DIR ?=
BENCH_CI_SMOKE_BASELINE_JSON ?=
BENCH_CI_SMOKE_MAX_REGRESSION_PCT ?= 20
BENCH_CI_SMOKE_COMPARE_MEMORY ?= 0
BENCH_CI_SMOKE_RUN_ID ?=
BENCHMARK_MD_PATH ?= BENCHMARK.md
CONFIG_PATH ?=
SERVER_ARGS ?=
CHECK_CONFIG_ARGS ?=
DOCKER_IMAGE ?= hatrie-cache:latest
DOCKERFILE ?= Dockerfile
DOCKER_CONTEXT ?= .
DOCKER_PLATFORM ?=
DOCKER_TARGET ?=
DOCKER_BUILD_ARGS ?=

.PHONY: test verify verify-go verify-race verify-c verify-frontend verify-ops verify-ci verify-benchmark-md-update backup restore restore-bundle restore-rehearsal doctor cluster-status storage-status storage-flush storage-compact server check-config docker-build bench bench-serialization bench-command-features bench-hatrie-command-features bench-hatrie-transport-features bench-redis-command-features bench-tarantool-command-features bench-command-comparison bench-ci-smoke benchmark-md command-support run generate-proto cli monitoring-server frontend-install frontend-dev frontend-check frontend-test frontend-build frontend-smoke frontend-backend-smoke

test: verify-go

verify: verify-go verify-c verify-frontend verify-ops

verify-go:
	./scripts/verify-go.sh

verify-race:
	./scripts/verify-race.sh

verify-c:
	./scripts/verify-c-policy-test.sh
	SANITIZE_C='$(SANITIZE_C)' SANITIZE_C_ALLOW_STRICT_OVERCOMMIT='$(SANITIZE_C_ALLOW_STRICT_OVERCOMMIT)' SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM='$(SANITIZE_C_ALLOW_LOW_COMMIT_HEADROOM)' SANITIZE_C_OVERCOMMIT_MEMORY_PATH='$(SANITIZE_C_OVERCOMMIT_MEMORY_PATH)' SANITIZE_C_MEMINFO_PATH='$(SANITIZE_C_MEMINFO_PATH)' SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB='$(SANITIZE_C_ASAN_MIN_COMMIT_HEADROOM_KB)' ./scripts/verify-c.sh

verify-frontend:
	./scripts/frontend.sh verify

verify-ops:
	./scripts/verify-ops.sh

verify-ci:
	./scripts/verify-ci.sh

verify-benchmark-md-update:
	./scripts/verify-benchmark-md-update.sh

backup:
	DATA_DIR='$(DATA_DIR)' BACKUP_DIR='$(BACKUP_DIR)' BACKUP_OVERWRITE='$(BACKUP_OVERWRITE)' ./scripts/backup.sh

restore:
	DATA_DIR='$(DATA_DIR)' BACKUP_DIR='$(BACKUP_DIR)' RESTORE_OVERWRITE='$(RESTORE_OVERWRITE)' ./scripts/restore.sh

restore-bundle:
	DATA_DIR='$(DATA_DIR)' RESTORE_BUNDLE_PATH='$(RESTORE_BUNDLE_PATH)' RESTORE_BUNDLE_OVERWRITE='$(RESTORE_BUNDLE_OVERWRITE)' ./scripts/restore-bundle.sh

restore-rehearsal:
	RESTORE_REHEARSAL_PATH='$(RESTORE_REHEARSAL_PATH)' RESTORE_REHEARSAL_WORK_DIR='$(RESTORE_REHEARSAL_WORK_DIR)' RESTORE_REHEARSAL_KEEP_WORK_DIR='$(RESTORE_REHEARSAL_KEEP_WORK_DIR)' RESTORE_REHEARSAL_RUNTIME_CHECK='$(RESTORE_REHEARSAL_RUNTIME_CHECK)' RESTORE_REHEARSAL_RUNTIME_GET='$(RESTORE_REHEARSAL_RUNTIME_GET)' RESTORE_REHEARSAL_RUNTIME_SERVER_BIN='$(RESTORE_REHEARSAL_RUNTIME_SERVER_BIN)' ./scripts/restore-rehearsal.sh

doctor:
	DOCTOR_PATH='$(DOCTOR_PATH)' ./scripts/doctor.sh

cluster-status:
	CLUSTER_PEER='$(CLUSTER_PEER)' CLUSTER_PROBE_NODES='$(CLUSTER_PROBE_NODES)' ./scripts/cluster-status.sh

storage-status:
	STORAGE_PEER='$(STORAGE_PEER)' ./scripts/storage-status.sh

storage-flush:
	STORAGE_PEER='$(STORAGE_PEER)' ./scripts/storage-flush.sh

storage-compact:
	STORAGE_PEER='$(STORAGE_PEER)' STORAGE_COMPACT_START_KEY='$(STORAGE_COMPACT_START_KEY)' STORAGE_COMPACT_LIMIT_KEY='$(STORAGE_COMPACT_LIMIT_KEY)' ./scripts/storage-compact.sh

server:
	CONFIG_PATH='$(CONFIG_PATH)' ./scripts/server.sh $(SERVER_ARGS)

check-config:
	CONFIG_PATH='$(CONFIG_PATH)' ./scripts/check-config.sh $(CHECK_CONFIG_ARGS)

docker-build:
	DOCKER_IMAGE='$(DOCKER_IMAGE)' DOCKERFILE='$(DOCKERFILE)' DOCKER_CONTEXT='$(DOCKER_CONTEXT)' DOCKER_PLATFORM='$(DOCKER_PLATFORM)' DOCKER_TARGET='$(DOCKER_TARGET)' ./scripts/docker-build.sh $(DOCKER_BUILD_ARGS)

bench:
	go test -run '^$$' -bench='$(BENCH)' -benchmem

bench-serialization:
	SERIALIZATION_BENCH='$(SERIALIZATION_BENCH)' BENCHTIME='$(BENCHTIME)' COUNT='$(COUNT)' ./scripts/benchmark-serialization.sh

bench-command-features:
	go test -run '^$$' -bench='^BenchmarkCommandFeature$$' -benchmem -count='$(COUNT)' $(if $(BENCHTIME),-benchtime='$(BENCHTIME)')

bench-hatrie-command-features:
	HATRIE_BENCH='$(HATRIE_COMMAND_BENCH)' BENCHTIME='$(BENCHTIME)' COUNT='$(COUNT)' BENCHMARK_ARTIFACT_DIR='$(BENCHMARK_ARTIFACT_DIR)' ./scripts/benchmark-hatrie-command-features.sh

bench-hatrie-transport-features:
	HATRIE_TRANSPORT_BENCH='$(HATRIE_TRANSPORT_BENCH)' BENCHTIME='$(BENCHTIME)' COUNT='$(COUNT)' ./scripts/benchmark-hatrie-transport-features.sh

bench-redis-command-features:
	REDIS_HOST='$(REDIS_HOST)' REDIS_PORT='$(REDIS_PORT)' REDIS_REQUESTS='$(REDIS_REQUESTS)' REDIS_CLIENTS='$(REDIS_CLIENTS)' REDIS_KEYSPACE='$(REDIS_KEYSPACE)' REDIS_START_DOCKER='$(REDIS_START_DOCKER)' REDIS_DOCKER_IMAGE='$(REDIS_DOCKER_IMAGE)' BENCHMARK_ARTIFACT_DIR='$(BENCHMARK_ARTIFACT_DIR)' ./scripts/benchmark-redis-command-features.sh

bench-tarantool-command-features:
	TARANTOOL_REQUESTS='$(TARANTOOL_REQUESTS)' TARANTOOL_KEYSPACE='$(TARANTOOL_KEYSPACE)' TARANTOOL_MEMTX_MEMORY='$(TARANTOOL_MEMTX_MEMORY)' TARANTOOL_BIN='$(TARANTOOL_BIN)' TARANTOOL_WORK_DIR='$(TARANTOOL_WORK_DIR)' BENCHMARK_ARTIFACT_DIR='$(BENCHMARK_ARTIFACT_DIR)' ./scripts/benchmark-tarantool-command-features.sh

bench-command-comparison:
	BENCHMARK_ARTIFACT_DIR='$(BENCHMARK_ARTIFACT_DIR)' ./scripts/benchmark-command-comparison.sh

bench-ci-smoke:
	BENCH_CI_SMOKE_BENCHTIME='$(BENCH_CI_SMOKE_BENCHTIME)' BENCH_CI_SMOKE_COUNT='$(BENCH_CI_SMOKE_COUNT)' BENCH_CI_SMOKE_COMMAND_BENCH='$(BENCH_CI_SMOKE_COMMAND_BENCH)' BENCH_CI_SMOKE_TRANSPORT_BENCH='$(BENCH_CI_SMOKE_TRANSPORT_BENCH)' BENCH_CI_SMOKE_SERIALIZATION_BENCH='$(BENCH_CI_SMOKE_SERIALIZATION_BENCH)' BENCH_CI_SMOKE_CHECK_THRESHOLDS='$(BENCH_CI_SMOKE_CHECK_THRESHOLDS)' BENCH_CI_SMOKE_MAX_COMMAND_NS_OP='$(BENCH_CI_SMOKE_MAX_COMMAND_NS_OP)' BENCH_CI_SMOKE_MAX_TRANSPORT_NS_OP='$(BENCH_CI_SMOKE_MAX_TRANSPORT_NS_OP)' BENCH_CI_SMOKE_MAX_SERIALIZATION_NS_OP='$(BENCH_CI_SMOKE_MAX_SERIALIZATION_NS_OP)' BENCH_CI_SMOKE_MAX_B_OP='$(BENCH_CI_SMOKE_MAX_B_OP)' BENCH_CI_SMOKE_MAX_ALLOCS_OP='$(BENCH_CI_SMOKE_MAX_ALLOCS_OP)' BENCH_CI_SMOKE_ARTIFACT_DIR='$(BENCH_CI_SMOKE_ARTIFACT_DIR)' BENCH_CI_SMOKE_BASELINE_JSON='$(BENCH_CI_SMOKE_BASELINE_JSON)' BENCH_CI_SMOKE_MAX_REGRESSION_PCT='$(BENCH_CI_SMOKE_MAX_REGRESSION_PCT)' BENCH_CI_SMOKE_COMPARE_MEMORY='$(BENCH_CI_SMOKE_COMPARE_MEMORY)' BENCH_CI_SMOKE_RUN_ID='$(BENCH_CI_SMOKE_RUN_ID)' ./scripts/benchmark-ci-smoke.sh

benchmark-md:
	BENCHMARK_ARTIFACT_DIR='$(BENCHMARK_ARTIFACT_DIR)' BENCHMARK_MD_PATH='$(BENCHMARK_MD_PATH)' ./scripts/update-benchmark-md.sh

command-support:
	./scripts/command-support.sh

run:
	@CMD='$(CMD)' ./scripts/run.sh

generate-proto:
	./scripts/generate-proto.sh

cli:
	./scripts/cli.sh $(ARGS)

monitoring-server:
	MONITORING_ADDR='$(MONITORING_ADDR)' MONITORING_WEB_DIR='$(MONITORING_WEB_DIR)' MONITORING_TLS_CERT='$(MONITORING_TLS_CERT)' MONITORING_TLS_KEY='$(MONITORING_TLS_KEY)' MONITORING_AUTH_TOKEN='$(MONITORING_AUTH_TOKEN)' AUDIT_LOG_PATH='$(AUDIT_LOG_PATH)' WRITE_PROTECTION='$(WRITE_PROTECTION)' RATE_LIMIT='$(RATE_LIMIT)' MONITORING_READ_HEADER_TIMEOUT='$(MONITORING_READ_HEADER_TIMEOUT)' MONITORING_IDLE_TIMEOUT='$(MONITORING_IDLE_TIMEOUT)' NODE_ID='$(NODE_ID)' TOPOLOGY_PATH='$(TOPOLOGY_PATH)' ELECTION_TIMEOUT='$(ELECTION_TIMEOUT)' REPLICATION='$(REPLICATION)' REPLICATION_ASYNC='$(REPLICATION_ASYNC)' REPLICATION_QUEUE_SIZE='$(REPLICATION_QUEUE_SIZE)' REPLICATION_RETRY_INTERVAL='$(REPLICATION_RETRY_INTERVAL)' REPLICATION_MAX_ATTEMPTS='$(REPLICATION_MAX_ATTEMPTS)' REPLICATION_DEAD_LETTER_LIMIT='$(REPLICATION_DEAD_LETTER_LIMIT)' REPLICATION_OUTBOX_PATH='$(REPLICATION_OUTBOX_PATH)' REPLICATION_CIRCUIT_BREAKER_FAILURES='$(REPLICATION_CIRCUIT_BREAKER_FAILURES)' REPLICATION_CIRCUIT_BREAKER_COOLDOWN='$(REPLICATION_CIRCUIT_BREAKER_COOLDOWN)' REPLICATION_WIRE_FORMAT='$(REPLICATION_WIRE_FORMAT)' REPLICATION_SYNC_INTERVAL='$(REPLICATION_SYNC_INTERVAL)' REPLICATION_SYNC_PREFIX='$(REPLICATION_SYNC_PREFIX)' ENFORCE_LEADER_WRITES='$(ENFORCE_LEADER_WRITES)' GRPC_ADDR='$(GRPC_ADDR)' GRPC_TLS_CERT='$(GRPC_TLS_CERT)' GRPC_TLS_KEY='$(GRPC_TLS_KEY)' GRPC_CLIENT_CA='$(GRPC_CLIENT_CA)' DB_PATH='$(DB_PATH)' DB_FORMAT='$(DB_FORMAT)' DB_SYNC_INTERVAL='$(DB_SYNC_INTERVAL)' DB_COMPACT_INTERVAL='$(DB_COMPACT_INTERVAL)' DB_COMPACT_START_KEY='$(DB_COMPACT_START_KEY)' DB_COMPACT_LIMIT_KEY='$(DB_COMPACT_LIMIT_KEY)' DB_HOT_LOAD='$(DB_HOT_LOAD)' DB_HOT_LOAD_MAX_BYTES='$(DB_HOT_LOAD_MAX_BYTES)' DB_HOT_LOAD_MAX_AGE='$(DB_HOT_LOAD_MAX_AGE)' DB_HOT_LOAD_MIN_HITS='$(DB_HOT_LOAD_MIN_HITS)' SNAPSHOT_PATH='$(SNAPSHOT_PATH)' SNAPSHOT_INTERVAL='$(SNAPSHOT_INTERVAL)' SNAPSHOT_FORMAT='$(SNAPSHOT_FORMAT)' JOURNAL_PATH='$(JOURNAL_PATH)' JOURNAL_FORMAT='$(JOURNAL_FORMAT)' JOURNAL_PULL_SOURCE='$(JOURNAL_PULL_SOURCE)' JOURNAL_PULL_STATE_PATH='$(JOURNAL_PULL_STATE_PATH)' JOURNAL_PULL_INTERVAL='$(JOURNAL_PULL_INTERVAL)' JOURNAL_PULL_TIMEOUT='$(JOURNAL_PULL_TIMEOUT)' JOURNAL_PULL_LIMIT='$(JOURNAL_PULL_LIMIT)' JOURNAL_PULL_MAX_BATCHES='$(JOURNAL_PULL_MAX_BATCHES)' ./scripts/monitoring-server.sh

frontend-install:
	./scripts/frontend.sh install

frontend-dev:
	./scripts/frontend.sh dev

frontend-check:
	./scripts/frontend.sh check

frontend-test:
	./scripts/frontend.sh test

frontend-build:
	./scripts/frontend.sh build

frontend-smoke:
	./scripts/frontend-smoke.sh

frontend-backend-smoke:
	./scripts/frontend-backend-smoke.sh
