package hatriecache

import core "hatrie_cache/hat/hatCache"

const DefaultPersistentStoreDiskReserveBytes = core.DefaultPersistentStoreDiskReserveBytes

const DefaultPersistentStoreBloomFilterBitsPerKey = core.DefaultPersistentStoreBloomFilterBitsPerKey
const MaxPersistentStoreBloomFilterBitsPerKey = core.MaxPersistentStoreBloomFilterBitsPerKey

var ErrPersistentStorageDiskReserveExceeded = core.ErrPersistentStorageDiskReserveExceeded
var ErrPersistentStorageDiskReserveUnavailable = core.ErrPersistentStorageDiskReserveUnavailable
var ConfigurePersistentStoreDiskReserveBytes = core.ConfigurePersistentStoreDiskReserveBytes
var PersistentStoreDiskReserveBytes = core.PersistentStoreDiskReserveBytes
var ConfigurePersistentStoreBloomFilterBitsPerKey = core.ConfigurePersistentStoreBloomFilterBitsPerKey
var PersistentStoreBloomFilterBitsPerKey = core.PersistentStoreBloomFilterBitsPerKey
