#!/usr/bin/env bash
set -euo pipefail

mode=${1:-plan}
tmp_root=${HATRIE_TMP_ROOT:-/tmp}
min_age_seconds=${HATRIE_TMP_MIN_AGE_SECONDS:-86400}
plan_file=${HATRIE_TMP_PLAN_FILE:-"$PWD/.hatrie-tmp-cleanup.plan"}

if [[ "$mode" != plan && "$mode" != apply ]]; then
  printf 'usage: %s [plan|apply]\n' "$0" >&2
  exit 2
fi

declare -A protected_paths=()
while IFS= read -r line; do
  case "$line" in
    "worktree "*)
      protected_paths[${line#worktree }]=1
      ;;
  esac
done < <(git worktree list --porcelain)

is_protected() {
  [[ ${protected_paths[$1]+yes} ]]
}

candidate_paths() {
  local now path mtime age
  now=$(date +%s)
  while IFS= read -r -d '' path; do
    is_protected "$path" && continue
    mtime=$(stat -c %Y -- "$path")
    age=$((now - mtime))
    (( age >= min_age_seconds )) || continue
    printf '%s\n' "$path"
  done < <(
    find "$tmp_root" -mindepth 1 -maxdepth 1 -type d -iname '*hatrie*' -print0 |
      sort -z
  )
}

if [[ "$mode" == plan ]]; then
  mapfile -t candidates < <(candidate_paths)
  printf 'Hatrie test temporary cleanup plan (age >= %ss):\n' "$min_age_seconds"
  printf '# Generated by %s; review before apply.\n' "$0" > "$plan_file"
  for path in "${candidates[@]}"; do
    printf '%s\n' "$path"
    printf '%s\n' "$path" >> "$plan_file"
  done
  printf 'Summary: %s candidate(s).\n' "${#candidates[@]}"
  printf 'Plan: %s\n' "$plan_file"
  exit 0
fi

if [[ ! -f "$plan_file" ]]; then
  printf 'cleanup plan not found: %s\n' "$plan_file" >&2
  exit 1
fi

removed=0
while IFS= read -r path; do
  [[ -z "$path" || "$path" == \#* ]] && continue
  case "$path" in
    "$tmp_root"/*) ;;
    *)
      printf 'refusing path outside %s: %s\n' "$tmp_root" "$path" >&2
      exit 1
      ;;
  esac
  if is_protected "$path"; then
    printf 'refusing active Git worktree: %s\n' "$path" >&2
    exit 1
  fi
  [[ -d "$path" ]] || continue
  rm -rf -- "$path"
  printf 'Removed %s\n' "$path"
  removed=$((removed + 1))
done < "$plan_file"
printf 'Removed %s candidate(s).\n' "$removed"
