// Command generate-root-api creates the root compatibility facade for hatCache.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const coreImportPath = "hatrie_cache/hat/hatCache"

func main() {
	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	coreDir := filepath.Join(root, "hat", "hatCache")
	pkg, err := build.Default.ImportDir(coreDir, 0)
	if err != nil {
		fatal(err)
	}
	files := append(append([]string{}, pkg.GoFiles...), pkg.CgoFiles...)
	sort.Strings(files)

	types := map[string]struct{}{}
	constants := map[string]struct{}{}
	variables := map[string]struct{}{}
	functions := map[string]struct{}{}
	for _, name := range files {
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(coreDir, name), nil, 0)
		if err != nil {
			fatal(err)
		}
		collect(file, types, constants, variables, functions)
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by scripts/generate-root-api.go; DO NOT EDIT.\n\n")
	source.WriteString("package hatriecache\n\n")
	source.WriteString("import (\n\t\"context\"\n\n\tcore \"")
	source.WriteString(coreImportPath)
	source.WriteString("\"\n)\n\n")
	writeAliases(&source, "type", types)
	writeAliases(&source, "const", constants)
	writeAliases(&source, "var", variables)
	for _, name := range sorted(functions) {
		if name == "QueryRows" {
			continue
		}
		fmt.Fprintf(&source, "var %s = core.%s\n", name, name)
	}
	source.WriteString("\nfunc QueryRows[T any](ctx context.Context, conn *SQLConn, query string, visit func(T) error) (int, error) {\n")
	source.WriteString("\treturn core.QueryRows[T](ctx, conn, query, visit)\n}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "api.go"), formatted, 0o644); err != nil {
		fatal(err)
	}
}

func collect(file *ast.File, types, constants, variables, functions map[string]struct{}) {
	for _, declaration := range file.Decls {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			if declaration.Recv == nil && declaration.Name.IsExported() {
				functions[declaration.Name.Name] = struct{}{}
			}
		case *ast.GenDecl:
			for _, specification := range declaration.Specs {
				switch specification := specification.(type) {
				case *ast.TypeSpec:
					if specification.Name.IsExported() {
						types[specification.Name.Name] = struct{}{}
					}
				case *ast.ValueSpec:
					for _, name := range specification.Names {
						if !name.IsExported() {
							continue
						}
						switch declaration.Tok {
						case token.CONST:
							constants[name.Name] = struct{}{}
						case token.VAR:
							variables[name.Name] = struct{}{}
						}
					}
				}
			}
		}
	}
}

func writeAliases(source *bytes.Buffer, keyword string, names map[string]struct{}) {
	for _, name := range sorted(names) {
		fmt.Fprintf(source, "%s %s = core.%s\n", keyword, name, name)
	}
	if len(names) > 0 {
		source.WriteByte('\n')
	}
}

func sorted(names map[string]struct{}) []string {
	result := make([]string, 0, len(names))
	for name := range names {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, strings.TrimSpace(err.Error()))
	os.Exit(1)
}
