#!/usr/bin/env bash
set -euo pipefail

go test -race ./hat/hatSql -run 'TestCompiledSQLNativeDataflowMatchesCompositeGroupedRows|TestCompiledSQLNativeDataflowCompositeGroupChecksContext|TestCompiledSQLNativeDataflowCompositeGroupRejectsUnsupportedRuntimeKey|TestCompiledSQLNativeDataflowCompositeGroupRejectsMaterializedShapes'
