#!/usr/bin/env bash
set -euo pipefail

test -f MATERIALIZED_VIEW_DEPENDENCY_GRAPH.md
rg -F 'MATERIALIZED_VIEW_DEPENDENCY_GRAPH.md' README.md ADOPTED_QUERY_ENGINE_IDEAS.md BENCHMARK.md
rg -F 'MZ-042' ENGINE_IDEAS.md BENCHMARK.md
rg -F 'RefreshChanged' MATERIALIZED_VIEW_DEPENDENCY_GRAPH.md ADOPTED_QUERY_ENGINE_IDEAS.md BENCHMARK.md
