#!/usr/bin/env bash
set -euo pipefail

test -f T217_IN_MEMORY_COLUMNAR_SPACE.md
rg -q 'T217_IN_MEMORY_COLUMNAR_SPACE\.md' README.md INSPIRATION_ROUND2.md ADOPTED_QUERY_ENGINE_IDEAS.md BENCHMARK.md
rg -q 'T217.*columnar|columnar.*T217' README.md INSPIRATION_ROUND2.md ADOPTED_QUERY_ENGINE_IDEAS.md BENCHMARK.md T217_IN_MEMORY_COLUMNAR_SPACE.md
