#!/usr/bin/env bash
set -euo pipefail

test -f T216_STORAGE_COMPACTION_SCHEDULER.md
rg -q 'T216_STORAGE_COMPACTION_SCHEDULER\.md' README.md INSPIRATION_ROUND2.md BENCHMARK.md
rg -q 'T216.*compaction|compaction.*T216' README.md INSPIRATION_ROUND2.md BENCHMARK.md T216_STORAGE_COMPACTION_SCHEDULER.md
