#!/usr/bin/env bash
set -euo pipefail

for file in C241_INCREMENTAL_CHUNK_DEDUP.md BENCHMARK.md README.md INSPIRATION_ROUND2.md ADOPTED_QUERY_ENGINE_IDEAS.md; do
  test -f "$file"
done
rg -q 'C241_INCREMENTAL_CHUNK_DEDUP.md' README.md INSPIRATION_ROUND2.md ADOPTED_QUERY_ENGINE_IDEAS.md
rg -q 'c241-incremental-backup-chunk-deduplication' BENCHMARK.md INSPIRATION_ROUND2.md ADOPTED_QUERY_ENGINE_IDEAS.md
rg -q 'ChunkSize: 0' C241_INCREMENTAL_CHUNK_DEDUP.md BENCHMARK.md ADOPTED_QUERY_ENGINE_IDEAS.md
